dist: focal

services:
  - docker

script:
  - ./make.sh all

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file_glob: true
  file:
    - ./binaries/*.zip
  on: 
    all_branches: true
    tags: true
