dist: focal

services:
  - docker

script:
  - ./make.sh all

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file:
    - ./binaries/*.zip
  on.tags: true
  on: 
    branch: main