dist: focal

services:
  - docker

script:
  - ./make.sh all

deploy:
  provider: releases
  api_key: "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"
  file_glob: true
  file:
    - ./binaries/*.zip
  on.tags: true